from typing import Protocol, runtime_checkable

from scylla.errors import PrepareError, RequestFailedError, SerializationError
from scylla.statement import Consistency

class RetryDecision:
    """
    Returned by the `decide_should_retry()` method of `RetryPolicy`. Instructs the driver on what
    to do about the request after it failed.
    """

    class RetrySameTarget(RetryDecision):
        """
        Request will be sent to the same shard on the same host.

        Attributes:
            consistency (`Consistency` | `None`): The consistency level to use for the retry.
                If set to `None`, the driver will reuse the same consistency level as the
                original failed request. Defaults to `None`.
        """

        @property
        def consistency(self) -> Consistency | None: ...
        def __init__(self, consistency: Consistency | None = None) -> None: ...

    class RetryNextTarget(RetryDecision):
        """
        Request will be sent to the next target generated by load balancing policy.

        Attributes:
            consistency (`Consistency` | `None`): The consistency level to use for the retry.
                If set to `None`, the driver will reuse the same consistency level as the
                original failed request. Defaults to `None`.
        """

        @property
        def consistency(self) -> Consistency | None: ...
        def __init__(self, consistency: Consistency | None = None) -> None: ...

    class DontRetry(RetryDecision):
        """Fails the whole request."""

        def __init__(self) -> None: ...

    class IgnoreWriteError(RetryDecision):
        """Will cause the driver to return an empty successful response."""

        def __init__(self) -> None: ...

class RequestInfo:
    """
    Information about a failed request.

    Attributes:
        error (`RequestFailedError` | `PrepareError` | `SerializationError`): The exception
            for the failed attempt. It is the same class that `execute` raises
            for this failure, for example `ReadTimeout`.

        is_idempotent (`bool`): A request is idempotent if it can be applied multiple times
            without changing the result of the initial application.
            If set to `true` we can be sure that it is idempotent.
            If set to `false` it is unknown whether it is idempotent.

        consistency (`Consistency`): Consistency with which the request failed.
    """

    @property
    def error(self) -> RequestFailedError | PrepareError | SerializationError: ...
    @property
    def is_idempotent(self) -> bool: ...
    @property
    def consistency(self) -> Consistency: ...

@runtime_checkable
class RetrySession(Protocol):
    """
    Used throughout a single request to decide when to retry it.
    After this request is finished it is destroyed or reset.
    """

    def __init__(self) -> None: ...
    def decide_should_retry(self, request_info: RequestInfo) -> RetryDecision: ...
    """Called after the request failed - decide what to do next."""

    def reset(self) -> None: ...
    """Reset before using for a new request."""

class DefaultRetrySession:
    """`RetrySession` for `DefaultRetryPolicy`."""

    def __init__(self) -> None: ...
    def decide_should_retry(self, request_info: RequestInfo) -> RetryDecision: ...
    def reset(self) -> None: ...

class DowngradingConsistencyRetrySession:
    """`RetrySession` for `DowngradingConsistencyRetryPolicy`."""

    def __init__(self) -> None: ...
    def decide_should_retry(self, request_info: RequestInfo) -> RetryDecision: ...
    def reset(self) -> None: ...

class FallthroughRetrySession:
    """`RetrySession` for `FallthroughRetryPolicy`."""

    def __init__(self) -> None: ...
    def decide_should_retry(self, request_info: RequestInfo) -> RetryDecision: ...
    def reset(self) -> None: ...

@runtime_checkable
class RetryPolicy(Protocol):
    """Specifies a policy used to decide when to retry a request."""

    def __init__(self) -> None: ...
    def new_session(self) -> RetrySession: ...
    """Called for each new request, starts a session of deciding about retries."""

class DefaultRetryPolicy:
    """Retries when there is a high chance that a retry might help."""

    def __init__(self) -> None: ...
    def new_session(self) -> RetrySession: ...

class DowngradingConsistencyRetryPolicy:
    """
    Retries with lower consistency level if it knows that the initial CL is unreachable.
    Also, it behaves as `DefaultRetryPolicy` when it believes that the initial CL is reachable.
    """

    def __init__(self) -> None: ...
    def new_session(self) -> RetrySession: ...

class FallthroughRetryPolicy:
    """Forwards all errors directly to the user, never retries."""

    def __init__(self) -> None: ...
    def new_session(self) -> RetrySession: ...
