class ScyllaError(Exception): ...
class RowIterationError(ScyllaError): ...

class DeserializationError(ScyllaError):
    column_name: str | None
    column_index: int | None
    inner_path: list[str] | None

class UnsupportedTypeDeserializationError(DeserializationError): ...
class DecodeFailedError(DeserializationError): ...
class PyConversionFailedError(DeserializationError): ...
class SessionConnectionError(ScyllaError): ...
class SessionConfigError(ScyllaError): ...
class StatementConversionError(ScyllaError): ...
class PrepareError(ScyllaError): ...
class ExecuteError(ScyllaError): ...
class SchemaAgreementError(ScyllaError): ...
class StatementConfigError(ScyllaError): ...
class BatchError(ScyllaError): ...

class SerializationError(ScyllaError):
    parameter: str | int | None

class UnsupportedTypeSerializationError(SerializationError): ...
class TypeMismatchSerializationError(SerializationError): ...
class ValueOverflowSerializationError(SerializationError): ...
class SerializeFailedError(SerializationError): ...
class PySerializationFailedError(SerializationError): ...
class ClusterStateTokenError(ScyllaError): ...
class UseKeyspaceError(ScyllaError): ...
class BadKeyspaceNameError(UseKeyspaceError): ...
class RequestError(UseKeyspaceError): ...
class KeyspaceNameMismatchError(UseKeyspaceError): ...
class RequestTimeoutError(UseKeyspaceError): ...
class RuntimeTaskJoinFailedError(UseKeyspaceError): ...
class AddressTranslationError(ScyllaError): ...
class HostFilterError(ScyllaError): ...
class TlsError(ScyllaError): ...
class LoadBalancingPolicyError(ScyllaError): ...
class RetryPolicyError(ScyllaError): ...
class SpeculativeExecutionPolicyError(ScyllaError): ...
