from scylla.policies.retry import CqlResponseKind, OperationType, WriteType
from scylla.statement import Consistency

class ScyllaError(Exception): ...
class InternalDriverError(ScyllaError): ...
class RowIterationError(ScyllaError): ...

class DeserializationError(ScyllaError):
    column_name: str | None
    column_index: int | None
    inner_path: list[str] | None

class UnsupportedTypeDeserializationError(DeserializationError): ...
class DecodeFailedError(DeserializationError): ...
class PyConversionFailedError(DeserializationError): ...
class SessionConnectionError(ScyllaError): ...
class SessionConfigError(ScyllaError): ...
class StatementConversionError(ScyllaError): ...

# Invalid input, rejected before sending - retrying won't help
class BadQuery(ScyllaError, ValueError): ...

class ValuesTooLongForKey(BadQuery):
    length: int
    max_length: int

class TooManyStatementsInBatch(BadQuery):
    count: int

class PartitionKeyExtractionFailed(BadQuery): ...
class PagingStateNotAllowed(BadQuery): ...

# Failures while executing a request
class ExecutionError(ScyllaError): ...

class OperationTimedOut(ExecutionError, TimeoutError):
    timeout: float

class NoHostAvailable(ExecutionError): ...
class MetadataError(ExecutionError): ...
class SchemaAgreementError(ExecutionError): ...
class ConnectionPoolError(ExecutionError): ...
class ConnectionPoolBroken(ConnectionPoolError): ...
class PoolInitializing(ConnectionPoolError): ...
class NodeDisabledByHostFilter(ConnectionPoolError): ...
class PrepareError(ExecutionError): ...

class RepreparedIdChanged(PrepareError):
    statement: str
    expected_id: bytes
    reprepared_id: bytes

class RepreparedIdMissingInBatch(PrepareError): ...
class RequestFailedError(ExecutionError): ...
class BrokenConnection(RequestFailedError): ...
class ConnectionBusy(RequestFailedError): ...
class NonfinishedPagingState(RequestFailedError): ...
class ProtocolError(RequestFailedError): ...
class ResponseParseError(ProtocolError): ...
class RequestSerializationError(ProtocolError): ...

class UnexpectedResponse(ProtocolError):
    response_kind: CqlResponseKind

# Errors returned by the database
class DatabaseError(RequestFailedError):
    reason: str

class RequestExecutionError(DatabaseError): ...

class Unavailable(RequestExecutionError):
    consistency: Consistency
    required: int
    alive: int

class ReadTimeout(RequestExecutionError):
    consistency: Consistency
    received: int
    required: int
    data_present: bool

class WriteTimeout(RequestExecutionError):
    consistency: Consistency
    received: int
    required: int
    write_type: WriteType

class ReadFailure(RequestExecutionError):
    consistency: Consistency
    received: int
    required: int
    numfailures: int
    data_present: bool

class WriteFailure(RequestExecutionError):
    consistency: Consistency
    received: int
    required: int
    numfailures: int
    write_type: WriteType

class FunctionFailure(RequestExecutionError):
    keyspace: str
    function: str
    arg_types: list[str]

class Overloaded(RequestExecutionError): ...
class IsBootstrapping(RequestExecutionError): ...
class TruncateError(RequestExecutionError): ...

class RateLimitReached(RequestExecutionError):
    op_type: OperationType
    rejected_by_coordinator: bool

class RequestValidationError(DatabaseError): ...
class CqlSyntaxError(RequestValidationError): ...
class InvalidRequest(RequestValidationError): ...
class Unauthorized(RequestValidationError): ...
class ServerConfigError(RequestValidationError): ...

class AlreadyExists(RequestValidationError):
    keyspace: str
    table: str

class AuthenticationFailed(DatabaseError): ...
class ServerError(DatabaseError): ...
class ServerProtocolError(DatabaseError): ...

class Unprepared(DatabaseError):
    statement_id: bytes

class UnknownDatabaseError(DatabaseError):
    code: int

# Other errors
class StatementConfigError(ScyllaError): ...
class BatchError(ScyllaError): ...

class SerializationError(ScyllaError):
    parameter: str | int | None

class UnsupportedTypeSerializationError(SerializationError): ...
class TypeMismatchSerializationError(SerializationError): ...
class ValueOverflowSerializationError(SerializationError): ...
class SerializeFailedError(SerializationError): ...
class PySerializationFailedError(SerializationError): ...
class ClusterStateTokenError(ScyllaError): ...
class UseKeyspaceError(ScyllaError): ...
class BadKeyspaceNameError(UseKeyspaceError): ...
class RequestError(UseKeyspaceError): ...
class KeyspaceNameMismatchError(UseKeyspaceError): ...
class RequestTimeoutError(UseKeyspaceError): ...
class RuntimeTaskJoinFailedError(UseKeyspaceError): ...
class AddressTranslationError(ScyllaError): ...
class HostFilterError(ScyllaError): ...
class TlsError(ScyllaError): ...
class LoadBalancingPolicyError(ScyllaError): ...
class RetryPolicyError(ScyllaError): ...
class RowFactoryError(ScyllaError): ...
class QueryMetadataError(ScyllaError): ...
class SpeculativeExecutionPolicyError(ScyllaError): ...

class FutureCancelledError(Exception):
    """Raised when a `DriverFuture` is cancelled via `cancel()`."""
