from scylla.policies.load_balancing import LoadBalancingPolicy
from scylla.results import RowFactoryLike

from .cluster.metadata import ColumnSpec
from .enums import Consistency, SerialConsistency
from .execution_profile import ExecutionProfile
from .policies.retry_policy import RetryPolicy
from .types import UnsetType

class PreparedStatement:
    """
    A prepared statement with immutable configuration.

    All `with_*` and `without_*` methods create and return a new instance of
    PreparedStatement with the modified configuration. The original instance
    (`self`) retains its old configuration and remains unchanged.
    """
    def with_execution_profile(self, profile: ExecutionProfile) -> PreparedStatement: ...
    def without_execution_profile(self) -> PreparedStatement: ...
    def with_row_factory(self, factory: RowFactoryLike) -> PreparedStatement: ...
    def without_row_factory(self) -> PreparedStatement: ...
    @property
    def execution_profile(self) -> ExecutionProfile | None: ...
    @property
    def row_factory(self) -> RowFactoryLike | None: ...
    def with_consistency(self, c: Consistency) -> PreparedStatement: ...
    def without_consistency(self) -> PreparedStatement: ...
    @property
    def consistency(self) -> Consistency | None: ...
    def with_serial_consistency(self, sc: SerialConsistency | None) -> PreparedStatement: ...
    def without_serial_consistency(self) -> PreparedStatement: ...
    @property
    def serial_consistency(self) -> SerialConsistency | None | UnsetType: ...
    def with_request_timeout(self, timeout: float | None) -> PreparedStatement: ...
    def without_request_timeout(self) -> PreparedStatement: ...
    @property
    def request_timeout(self) -> float | None | UnsetType: ...
    def with_page_size(self, page_size: int) -> PreparedStatement: ...
    @property
    def page_size(self) -> int: ...
    def with_load_balancing_policy(self, policy: LoadBalancingPolicy) -> PreparedStatement: ...
    def without_load_balancing_policy(self) -> PreparedStatement: ...
    @property
    def load_balancing_policy(self) -> LoadBalancingPolicy | None: ...
    def with_retry_policy(self, policy: RetryPolicy) -> PreparedStatement: ...
    def without_retry_policy(self) -> PreparedStatement: ...
    @property
    def retry_policy(self) -> RetryPolicy | None: ...
    def set_is_idempotent(self, is_idempotent: bool) -> PreparedStatement: ...
    @property
    def is_idempotent(self) -> bool: ...
    @property
    def query_id(self) -> bytes:
        """
        Retrieves the ID of this prepared statement.
        """
    @property
    def bind_columns(self) -> tuple[ColumnSpec, ...]:
        """
        Specifications of the bind variables of this statement.
        """
    @property
    def partition_key_indexes(self) -> tuple[int, ...]:
        """
        Bind variable indexes of the partition key columns, in partition key order.

        Element ``i`` is the index into ``bind_columns`` of the ``i``-th component of the
        partition key, so the tuple can be used directly to build a routing key.
        """
    @property
    def result_columns(self) -> tuple[ColumnSpec, ...]:
        """
        Specifications of the columns this statement returns.

        May be empty until the statement has been executed once: for some statements the
        server sends no result metadata in response to PREPARE, only to EXECUTE.
        """

class Statement:
    """
    A statement with immutable configuration.

    All `with_*` and `without_*` methods create and return a new instance of
    Statement with the modified configuration. The original instance
    (`self`) retains its old configuration and remains unchanged.
    """

    contents: str
    def __init__(self, query_str: str) -> None: ...
    def with_execution_profile(self, profile: ExecutionProfile) -> Statement: ...
    def without_execution_profile(self) -> Statement: ...
    def with_row_factory(self, factory: RowFactoryLike) -> Statement: ...
    def without_row_factory(self) -> Statement: ...
    @property
    def row_factory(self) -> RowFactoryLike | None: ...
    @property
    def execution_profile(self) -> ExecutionProfile | None: ...
    def with_consistency(self, c: Consistency) -> Statement: ...
    def without_consistency(self) -> Statement: ...
    @property
    def consistency(self) -> Consistency | None: ...
    def with_serial_consistency(self, sc: SerialConsistency | None) -> Statement: ...
    def without_serial_consistency(self) -> Statement: ...
    @property
    def serial_consistency(self) -> SerialConsistency | None | UnsetType: ...
    def with_request_timeout(self, timeout: float | None) -> Statement: ...
    def without_request_timeout(self) -> Statement: ...
    @property
    def request_timeout(self) -> float | None | UnsetType: ...
    def with_page_size(self, page_size: int) -> Statement: ...
    @property
    def page_size(self) -> int: ...
    def with_load_balancing_policy(self, policy: LoadBalancingPolicy) -> Statement: ...
    def without_load_balancing_policy(self) -> Statement: ...
    @property
    def load_balancing_policy(self) -> LoadBalancingPolicy | None: ...
    def with_retry_policy(self, policy: RetryPolicy) -> Statement: ...
    def without_retry_policy(self) -> Statement: ...
    @property
    def retry_policy(self) -> RetryPolicy | None: ...
    def set_is_idempotent(self, is_idempotent: bool) -> Statement: ...
    @property
    def is_idempotent(self) -> bool: ...
